'use client';

import type { Lecture } from '../../lib/supabase/types';

interface TranscriptViewProps {
  lecture: Lecture;
}

export function TranscriptView({ lecture }: TranscriptViewProps) {
  if (!lecture.transcript) {
    return (
      <div
        style={{
          display: 'flex',
          flexDirection: 'column',
          alignItems: 'center',
          justifyContent: 'center',
          minHeight: '60vh',
          gap: '1rem',
          padding: '2rem'
        }}
      >
        <div style={{ fontSize: '4rem' }}>📄</div>
        <h3 style={{ fontSize: '1.5rem', margin: 0, color: 'var(--text-primary)' }}>
          No Transcript Available
        </h3>
        <p style={{ color: 'var(--text-muted)', textAlign: 'center', maxWidth: '400px' }}>
          This lecture doesn&apos;t have a transcript yet. The transcription may have failed or is still processing.
        </p>
      </div>
    );
  }

  return (
    <div style={{ maxWidth: '900px', margin: '0 auto', padding: '2rem' }}>
      <div
        style={{
          background: 'var(--surface-panel)',
          borderRadius: '1rem',
          padding: '2rem',
          border: '1px solid var(--border-medium)',
          boxShadow: 'var(--shadow-panel)'
        }}
      >
        <div style={{ marginBottom: '1.5rem', paddingBottom: '1rem', borderBottom: '1px solid var(--border-subtle)' }}>
          <h2 style={{ fontSize: '1.5rem', margin: 0, color: 'var(--text-primary)' }}>
            Transcript
          </h2>
          <p style={{ margin: '0.5rem 0 0 0', fontSize: '0.9rem', color: 'var(--text-muted)' }}>
            Auto-generated by Deepgram
          </p>
        </div>

        <div
          style={{
            color: 'var(--text-secondary)',
            lineHeight: 1.8,
            fontSize: '1.05rem',
            whiteSpace: 'pre-wrap',
            wordBreak: 'break-word'
          }}
        >
          {lecture.transcript}
        </div>

        {/* Copy button */}
        <div style={{ marginTop: '2rem', display: 'flex', gap: '0.75rem' }}>
          <button
            onClick={() => {
              navigator.clipboard.writeText(lecture.transcript || '');
              // TODO: Add toast notification
            }}
            style={{
              padding: '0.75rem 1.5rem',
              borderRadius: '0.5rem',
              border: '1px solid var(--border-strong)',
              background: 'var(--surface-panel-faint)',
              color: 'var(--text-secondary)',
              fontWeight: 600,
              cursor: 'pointer',
              fontSize: '0.9rem',
              display: 'flex',
              alignItems: 'center',
              gap: '0.5rem'
            }}
          >
            📋 Copy to Clipboard
          </button>
        </div>
      </div>
    </div>
  );
}
